apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "warewulf.fullname" . }}-bootstrap
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.bootstrapScript }}
  bootstrap.sh: |
{{ .Values.bootstrapScript | indent 4 }}
  {{- end }}
  {{- if .Values.warewulfConf }}
  warewulf.conf: |
{{ .Values.warewulfConf | indent 4 }}
  {{- end }}
  {{- if .Values.slurmOverlay }}
  slurm-overlay.sh: |
{{ .Values.slurmOverlay | indent 4 }}
  {{- end }}
