# https://github.com/warewulf/warewulf-node-images/blob/main/rockylinux-9/Containerfile
FROM docker.io/rockylinux/rockylinux:9
RUN dnf update -y
RUN dnf install -y --allowerasing \
      coreutils \
      cpio \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel-core \
      kernel-modules \
      net-tools \
      NetworkManager \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      wget \
      which \
    && dnf remove -y selinux-policy \
    && dnf clean all
RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061
RUN userdel systemd-coredump # remove unused dynamic system user
COPY excludes /etc/warewulf/
COPY image_exit.sh /etc/warewulf/
RUN ln -sf image_exit.sh /etc/warewulf/container_exit.sh && /etc/warewulf/image_exit.sh
RUN dnf -y install \
      policycoreutils-python-utils \
      selinux-policy-targeted
RUN semanage fcontext -N -a -t bin_t /warewulf/wwclient || true
RUN update-crypto-policies --set FIPS
