image: ghcr.io/ezrizhu/puppy/warewulf:latest
imagePullPolicy: Always
hostNetwork: true

# k8s secrets ie slurm key
secrets: []

# warewulf.conf
warewulfConf: ""

# Slurm overlay setup script
slurmOverlay: ""

# CT startup
bootstrapScript: ""

resources: {}
