apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm-operator-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm-operator-crds
    targetRevision: 1.2.0
  destination:
    server: https://kubernetes.default.svc
    namespace: slinky
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
