apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slurm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/slinkyproject/charts
    chart: slurm
    targetRevision: 1.2.0
    helm:
      values: |
        accounting:
          enabled: true
        nodesets:
          slinky:
            replicas: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: slurm
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
